repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        exclude: ^.vscode/.*\.json$
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: just
        entry: just --fmt --unstable
        files: |
          (?x)^(
            .justfile|
            justfile
          )$
        language: system
        name: just
        pass_filenames: false
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
