= tio Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:tio: https://github.com/tio/tio[tio]

My configuration files for the {tio} serial device tool.

== Usage

This repository contains the configuration files for {tio} for the various devices I connect to over serial.

. Install {just} by following the instructions in the https://github.com/casey/just?tab=readme-ov-file#installation[installation section].

. Clone this repository.
+
[,sh]
----
git clone https://github.com/jwillikers/tio-config.git
----

. Change to the repository directory.
+
[,sh]
----
cd tio-config
----

. Run `just` to install everything.
+
[,sh]
----
just
----

. Log out and back in for the user's membership in the `dialout` group to take effect.

. Run `tio` followed by the desired device in the configuration file to open a serial console.
+
[,sh]
----
tio rpi4
----

== References

* https://github.com/tio/tio/blob/master/example/config[tio Example Config]
* https://wiki.archlinux.org/title/working_with_the_serial_console[Arch Linux Wiki: Working with the serial console]

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

== Copyright

© 2023-2024 Jordan Williams

== Authors

mailto:{email}[{author}]
